// This script is designed to test the solidity smart contract - SuppyChain.sol -- and the various functions within
// Declare a variable and assign the compiled smart contract artifact
const SupplyChain = artifacts.require('SupplyChain')
// import package to test event emissions
const truffleAssert = require('truffle-assertions')

contract('SupplyChain', function (accounts) {
  // Declare few constants and assign a few sample accounts generated by ganache-cli
  let upc = 1
  const msn = 1
  const ownerID = accounts[0]
  const originManufacturerName = 'Bosch'
  const originPlant = 'Aurich'
  const equipmentID = 1
  const componentNotes = 'Best parts for Galleys'
  var componentState = 0
  const supplierID = accounts[1]
  const transporterID = accounts[2]
  const manufacturerID = accounts[3]
  const customerID = accounts[4]
  const emptyAddress = '0x0000000000000000000000000000000000000000'

  console.log('ganache-cli accounts used here...')
  console.log('Contract Owner: accounts[0] ', accounts[0])
  console.log('Supplier: accounts[1] ', accounts[1])
  console.log('Transporter: accounts[2] ', accounts[2])
  console.log('Manufacturer: accounts[3] ', accounts[3])
  console.log('Customer: accounts[4] ', accounts[4])
  // const supplyChain = SupplyChain.deployed()
  // supplyChain.then(result => console.log(result.contract.events))
  // 1st test
  it('can add a Supplier Role to an address', async () => {
    const supplyChain = await SupplyChain.deployed()
    assert.equal(await supplyChain.isSupplier(supplierID), false)
    const tx = await supplyChain.addSupplier(supplierID, 'I am a supplier')
    assert.equal(await supplyChain.isSupplier(supplierID), true)
    assert.equal(await supplyChain.getNameSupplier(supplierID), 'I am a supplier')
    truffleAssert.eventEmitted(tx, 'SupplierAdded', ev => {
      return ev.account === supplierID && ev.name === 'I am a supplier'
    })
  })

  // 2nd Test
  it('can renounce a Supplier role', async () => {
    const supplyChain = await SupplyChain.deployed()
    assert.equal(await supplyChain.isSupplier(ownerID), true)
    await supplyChain.renounceSupplier({ from: ownerID })
    assert.equal(await supplyChain.isSupplier(ownerID), false)
  })
  // 3rd Test
  it('receiveComponent(): a supplier can receive a component', async () => {
    const supplyChain = await SupplyChain.deployed()
    // Mark a Component as received by calling function receiveComponent()
    const tx = await supplyChain.receiveComponent(
      upc,
      originManufacturerName,
      originPlant,
      equipmentID,
      componentNotes,
      { from: supplierID })
    // Retrieve saved Component from blockchain with fetchComponent()
    const resultFetch = await supplyChain.fetchComponent.call(upc)

    // Verify the result set
    assert.equal(resultFetch[0], upc, 'Error: Invalid item UPC')
    assert.equal(resultFetch[1], supplierID, 'Error: Missing or Invalid ownerID')
    assert.equal(resultFetch[2], originManufacturerName, 'Error: Missing or Invalid originManufacturerName')
    assert.equal(resultFetch[3], originPlant, 'Error: Missing or Invalid originPlant')
    assert.equal(resultFetch[4], equipmentID, 'Error: Missing or Invalid equipmentID')
    assert.equal(resultFetch[5], componentNotes, 'Error: Missing or Invalid componentsNotes')
    assert.equal(resultFetch[6], 6, 'Error: Missing or Invalid componentState')
    assert.equal(resultFetch[7], supplierID, 'Error: Missing or Invalid supplierID')
    assert.equal(resultFetch[8], componentState, 'Error: Missing or Invalid componentState')
    // check for event emission:
    truffleAssert.eventEmitted(tx, 'Received', ev => {
      return ev.asset === 'Component' && ev.id == upc
    })
    upc++
  })

  // 2nd Test
  it('orderEquipment(): a manufacturer can order an equipment', async () => {
    const supplyChain = await SupplyChain.deployed()
    // assign manufacturer role
    await supplyChain.addManufacturer(manufacturerID, 'I am a manufacturer')
    // Mark an equipment as Ordered by calling function orderEquipment()
    const tx = await supplyChain.orderEquipment(
      upc,
      supplierID,
      msn,
      { from: manufacturerID })

    // Retrieve saved equipment from blockchain  with fetchEquipment()
    const resultFetch = await supplyChain.fetchEquipment(upc)

    // Verify the result set
    assert.equal(resultFetch[0], upc, 'Error: Invalid item UPC')
    assert.equal(resultFetch[1], emptyAddress, 'Error: owner address should be empty at this stage')
    assert.equal(resultFetch[2], "", 'Error: originPlant should be empty at this stage')
    assert.equal(resultFetch[3], msn, 'Error: Missing or Invalid msn')
    assert.equal(resultFetch[4], 10, 'Error: Missing or Invalid price')
    assert.equal(resultFetch[5], "", 'Error: Missing or Invalid equipmentNotes')
    assert.equal(resultFetch[6], 1, 'Error: Missing or Invalid equipmentState')
    assert.equal(resultFetch[7], supplierID, 'Error: Missing or Invalid supplierID')
    assert.equal(resultFetch[8], await supplyChain.getNameSupplier(supplierID), 'Error: Missing or Invalid supplier name')
    // check for event emission:
    truffleAssert.eventEmitted(tx, 'Ordered', ev => {
      return ev.asset === 'Equipment' && ev.id == 2
    })
    upc++
  })
/*
    // 3rd Test
    it('Testing smart contract function packItem() that allows a farmer to pack coffee', async() => {
        const supplyChain = await SupplyChain.deployed()

        // Declare and Initialize a variable for event


        // Watch the emitted event Packed()


        // Mark an item as Packed by calling function packItem()


        // Retrieve the just now saved item from blockchain by calling function fetchItem()


        // Verify the result set

    })

    // 4th Test
    it('Testing smart contract function sellItem() that allows a farmer to sell coffee', async() => {
        const supplyChain = await SupplyChain.deployed()

        // Declare and Initialize a variable for event


        // Watch the emitted event ForSale()


        // Mark an item as ForSale by calling function sellItem()


        // Retrieve the just now saved item from blockchain by calling function fetchItem()


        // Verify the result set

    })

    // 5th Test
    it('Testing smart contract function buyItem() that allows a distributor to buy coffee', async() => {
        const supplyChain = await SupplyChain.deployed()

        // Declare and Initialize a variable for event


        // Watch the emitted event Sold()
        var event = supplyChain.Sold()


        // Mark an item as Sold by calling function buyItem()


        // Retrieve the just now saved item from blockchain by calling function fetchItem()


        // Verify the result set

    })

    // 6th Test
    it('Testing smart contract function shipItem() that allows a distributor to ship coffee', async() => {
        const supplyChain = await SupplyChain.deployed()

        // Declare and Initialize a variable for event


        // Watch the emitted event Shipped()


        // Mark an item as Sold by calling function buyItem()


        // Retrieve the just now saved item from blockchain by calling function fetchItem()


        // Verify the result set

    })

    // 7th Test
    it('Testing smart contract function receiveItem() that allows a retailer to mark coffee received', async() => {
        const supplyChain = await SupplyChain.deployed()

        // Declare and Initialize a variable for event


        // Watch the emitted event Received()


        // Mark an item as Sold by calling function buyItem()


        // Retrieve the just now saved item from blockchain by calling function fetchItem()


        // Verify the result set

    })

    // 8th Test
    it('Testing smart contract function purchaseItem() that allows a consumer to purchase coffee', async() => {
        const supplyChain = await SupplyChain.deployed()

        // Declare and Initialize a variable for event


        // Watch the emitted event Purchased()


        // Mark an item as Sold by calling function buyItem()


        // Retrieve the just now saved item from blockchain by calling function fetchItem()


        // Verify the result set

    })

    // 9th Test
    it('Testing smart contract function fetchItemBufferOne() that allows anyone to fetch item details from blockchain', async() => {
        const supplyChain = await SupplyChain.deployed()

        // Retrieve the just now saved item from blockchain by calling function fetchItem()


        // Verify the result set:

    })

    // 10th Test
    it('Testing smart contract function fetchItemBufferTwo() that allows anyone to fetch item details from blockchain', async() => {
        const supplyChain = await SupplyChain.deployed()

        // Retrieve the just now saved item from blockchain by calling function fetchItem()


        // Verify the result set:

    })
*/
})
